apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-world-k8s
  name: hello-world-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-k8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-k8s
    spec:
      containers:
      - image: springland/hello-world-docker
        name: hello-world-docker
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world-k8s
  name: hello-world-k8s
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-k8s
  type: ClusterIP
status:
  loadBalancer: {}
